In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"D:\netflix\tmdbdf.csv")
df= df.head(10000)

In [3]:
df.shape

(10000, 8)

In [4]:
df.isna().sum()

Unnamed: 0       0
index            0
id               0
title            0
overview         0
keywords       507
genres           2
poster_path      0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.describe()

         Unnamed: 0         index            id
count  10000.000000  10000.000000  1.000000e+04
mean    5001.159100   5001.159100  1.863105e+05
std     2888.725125   2888.725125  2.484923e+05
min        0.000000      0.000000  2.000000e+00
25%     2499.750000   2499.750000  1.016450e+04
50%     4999.500000   4999.500000  3.638700e+04
75%     7502.250000   7502.250000  3.399895e+05
max    10005.000000  10005.000000  1.151534e+06

In [7]:
df.describe(include=object)

,title,overview,keywords,genres,poster_path
count,10000,10000,9493,9998,10000
unique,9659,9998,9350,2115,10000
top,Beauty and the Beast,Wilbur the pig is scared of the end of the sea...,womandirector,Comedy,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg
freq,4,2,22,673,1

In [8]:
df['tags'] = df['overview'].fillna(' ')+df['keywords'].fillna(' ')+df['genres'].fillna(' ')
df['tags']

0       Cobb, a skilled thief who commits corporate es...
1       The adventures of a group of explorers who mak...
2       Batman raises the stakes in his war on crime. ...
3       In the 22nd century, a paraplegic Marine is di...
4       When an unexpected enemy emerges and threatens...
                              ...
9995    Thomas was once renowned as a young tennis pro...
9996    Country girl Rebecca has spent most of her lif...
9997    A shy boy is unable to make friends in Yazoo C...
9998    Fabio struggles with a cumbersome father and a...
9999    Mirko and Manolo are best friends and live in ...
Name: tags, Length: 10000, dtype: object

In [9]:
df['tags'].isna().sum()

np.int64(0)

### Lower case

In [10]:
df['tags'] = df['tags'].apply(lambda x:x.lower())

### Punctuations

df['tags'] = df['tags'].str.replace(r'[^\w\s]','',regex = True)
df['tags']

### Stemming

In [11]:
from nltk.stem import PorterStemmer

In [12]:
ps = PorterStemmer()

In [13]:
def stemming(word):
    y = []
    for i in word.split():
        y.append(ps.stem(i))
    return ' ' .join(y)

In [14]:
df['tags'] = df['tags'].apply(stemming)
df['tags']

0       cobb, a skill thief who commit corpor espionag...
1       the adventur of a group of explor who make use...
2       batman rais the stake in hi war on crime. with...
3       in the 22nd century, a parapleg marin is dispa...
4       when an unexpect enemi emerg and threaten glob...
                              ...
9995    thoma wa onc renown as a young tenni prodigy, ...
9996    countri girl rebecca ha spent most of her life...
9997    a shi boy is unabl to make friend in yazoo cit...
9998    fabio struggl with a cumbersom father and a ca...
9999    mirko and manolo are best friend and live in t...
Name: tags, Length: 10000, dtype: object

### Converting into vectors

In [15]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [16]:
tf = TfidfVectorizer(max_features=21000,stop_words='english')

In [17]:
vector = tf.fit_transform(df['tags'])

In [18]:
tf.get_feature_names_out().tolist()

['00',
 '000',
 '006',
 '007',
 '01',
 '05pm',
 '10',
 '100',
 '1000',
 '100th',
 '101',
 '1021',
 '103',
 '104th',
 '108',
 '10b',
 '10th',
 '10thcentury',
 '11',
 '111',
 '117',
 '118',
 '11drama',
 '11th',
 '11thcentury',
 '12',
 '120',
 '1200',
 '12th',
 '12thcentury',
 '13',
 '13th',
 '13thcentury',
 '14',
 '1453',
 '1492',
 '14th',
 '14thcentury',
 '14thcenturyadventure',
 '14thcenturyhorror',
 '15',
 '150',
 '15th',
 '15thcentury',
 '16',
 '1600s',
 '16th',
 '16thcentury',
 '16thcenturyaction',
 '17',
 '17th',
 '17thcentury',
 '17thcenturydrama',
 '18',
 '1800',
 '1800s',
 '1820s',
 '1830',
 '1843',
 '1850',
 '1850s',
 '1860s',
 '1862',
 '1863',
 '1870s',
 '1870swestern',
 '1879',
 '1880',
 '1890',
 '1890s',
 '1892',
 '1897',
 '18th',
 '18thcentury',
 '18thcenturydrama',
 '19',
 '1900',
 '1900s',
 '1900sadventure',
 '1900sdrama',
 '1900sfantasy',
 '1900swestern',
 '1905',
 '1910',
 '1910s',
 '1914',
 '1916',
 '1917',
 '1918',
 '1920',
 '1920s',
 '1920scomedy',
 '1920sdrama',
 '1922',
 '1925',
 '1927',
 '1930',
 '1930s',
 '1930sadventure',
 '1930scomedy',
 '1930scrime',
 '1930sdrama',
 '1931',
 '1933',
 '1935',
 '1936',
 '1937',
 '1938',
 '1939',
 '1940',
 '1940s',
 '1940saction',
 '1940scomedy',
 '1940scrime',
 '1940sdrama',
 '1940sromance',
 '1940sthriller',
 '1940swar',
 '1941',
 '1942',
 '1943',
 '1944',
 '1945',
 '1946',
 '1947',
 '1949',
 '1950',
 '1950s',
 '1950saction',
 '1950scomedy',
 '1950scrime',
 '1950sdrama',
 '1950sthriller',
 '1952',
 '1953',
 '1954',
 '1955',
 '1956',
 '1957',
 '1958',
 '1959',
 '1960',
 '1960s',
 '1960saction',
 '1960sadventure',
 '1960scomedi',
 '1960scomedy',
 '1960scrime',
 '1960sdrama',
 '1961',
 '1962',
 '1963',
 '1964',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1980s',
 '1980saction',
 '1980scomedy',
 '1980scrime',
 '1980sdrama',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1990s',
 '1990sanimation',
 '1990scomedy',
 '1990scrime',
 '1990sdrama',
 '1990sfantasy',
 '1990shorror',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '19animation',
 '19comedi',
 '19th',
 '19thcentury',
 '19thcenturyaction',
 '19thcenturyadventure',
 '19thcenturyanimation',
 '19thcenturydrama',
 '19thcenturyromance',
 '19thcenturythriller',
 '19thcenturywestern',
 '1stcentury',
 '1stcenturyfamily',
 '20',
 '200',
 '2000',
 '2000s',
 '2000sdrama',
 '2000ssciencefiction',
 '2000sthriller',
 '2001',
 '2002',
 '2003',
 '2004',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2010s',
 '2011',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2024',
 '2028',
 '2029',
 '2030s',
 '2030saction',
 '2030scrime',
 '2030sdrama',
 '2030ssciencefiction',
 '2035',
 '2040s',
 '2040saction',
 '2049',
 '2050s',
 '2060s',
 '2070saction',
 '20s',
 '20th',
 '21',
 '21st',
 '22',
 '22nd',
 '22ndcentury',
 '23',
 '23rd',
 '23rdcentury',
 '24',
 '25',
 '250',
 '26',
 '27',
 '28',
 '29',
 '2ndcentury',
 '30',
 '300',
 '30s',
 '30th',
 '31',
 '33',
 '34',
 '35',
 '350',
 '37',
 '38',
 '39',
 '3d',
 '3danimation',
 '3po',
 '40',
 '400',
 '40th',
 '42',
 '43',
 '45',
 '47',
 '476',
 '48',
 '49',
 '4th',
 '4thofjuly',
 '50',
 '500',
 '50th',
 '51',
 '52',
 '533',
 '54',
 '55',
 '59',
 '5thcenturybc',
 '60',
 '600',
 '60s',
 '62',
 '69',
 '6th',
 '70',
 '70s',
 '72',
 '75',
 '75th',
 '7th',
 '7thcenturyaction',
 '80',
 '800',
 '80sthrowback',
 '84',
 '86',
 '90',
 '90s',
 '90th',
 '911',
 '94',
 '95',
 '98',
 '99',
 '9th',
 'aaron',
 'aba',
 'aback',
 'abahachi',
 'abandon',
 'abandoned',
 'abandonedbaby',
 'abandonedbymother',
 'abandonedhouse',
 'abandonedmine',
 'abandonment',
 'abba',
 'abbey',
 'abbi',
 'abby',
 'abc',
 'abduct',
 'abducted',
 'abduction',
 'abductiondrama',
 'abductions',
 'abductionthriller',
 'abductors',
 'abe',
 'abid',
 'abigail',
 'abil',
 'abilities',
 'abl',
 'abnorm',
 'aboard',
 'abod',
 'abolitionist',
 'aborigin',
 'aboriginal',
 'aborigine',
 'abort',
 'abortion',
 'abortiondrama',
 'abov',
 'abra',
 'abraham',
 'abrahamlincoln',
 'abroad',
 'abrupt',
 'abruptli',
 'absenc',
 'absence',
 'absent',
 'absentparent',
 'absolut',
 'absorb',
 'absorbed',
 'absurd',
 'absurdcomedy',
 'absurdhorror',
 'absurdism',
 'absurdist',
 'abus',
 'abuse',
 'abused',
 'abusedwoman',
 'abuseofpower',
 'abusive',
 'abusivefamily',
 'abusivefather',
 'abusivefatherdrama',
 'abusivehusband',
 'abusivemarriage',
 'abusivemother',
 'abusiverelationship',
 'abusivestepfather',
 'aca',
 'academ',
 'academi',
 'academia',
 'academic',
 'academy',
 'acapella',
 'acapulco',
 'acceler',
 'accents',
 'accept',
 'acceptance',
 'accepts',
 'access',
 'accid',
 'accident',
 'accidental',
 'accidentaldeath',
 'accidentalkilling',
 'accidentally',
 'accidentcomedy',
 'accidentdrama',
 'accidents',
 'accio',
 'acclaim',
 'acclim',
 'accommod',
 'accompani',
 'accomplic',
 'accomplice',
 'accomplices',
 'accomplish',
 'accord',
 'accost',
 'account',
 'accountant',
 'accounts',
 'accumul',
 'accus',
 'accusation',
 'accusations',
 'accusedofmurder',
 'accustom',
 'ace',
 'ach',
 'achiev',
 'achievements',
 'acid',
 'acknowledg',
 'acm',
 'acoust',
 'acquaint',
 'acquaintance',
 'acquaintances',
 'acquir',
 'acquit',
 'acr',
 'acrobat',
 'acronym',
 'acrophobia',
 'act',
 'action',
 'actioncomedy',
 'actionhero',
 'actionheroact',
 'actionheroaction',
 'actionheroadventure',
 'actionherocrime',
 'actionherodrama',
 'actionherothriller',
 'actions',
 'activ',
 'activist',
 'activistdrama',
 'activities',
 'activity',
 'actor',
 'actordrama',
 'actorplayingthemselfcomedy',
 'actors',
 'actress',
 'acts',
 'actual',
 'acupuncture',
 'acut',
 'ad',
 'ada',
 'adalin',
 'adam',
 'adamandeve',
 'adams',
 'adapt',
 'adaptation',
 'add',
 'addam',
 'addi',
 'addict',
 'addicted',
 'addiction',
 'addictionrecovery',
 'addicts',
 'addison',
 'addit',
 'additionally',
 'addl',
 'address',
 'adel',
 'adelaid',
 'adept',
 'adjust',
 'adler',
 'administ',
 'administr',
 'administrator',
 'admir',
 'admiral',
 'admiration',
 'admired',
 'admiring',
 'admit',
 'admonit',
 'adolesc',
 'adolescence',
 'adolf',
 'adolfhitler',
 'adolfhitlerdrama',
 'adoni',
 'adopt',
 'adopted',
 'adoptedchild',
 'adoptedson',
 'adoption',
 'adoptivefather',
 'adoptivemother',
 'ador',
 'adorable',
 'adores',
 'adoring',
 'adorn',
 'adrenalin',
 'adrenaline',
 'adrenalinejunkie',
 'adrian',
 'adriana',
 'adrien',
 'adrift',
 'adult',
 'adultanimation',
 'adultanimationaction',
 'adultanimationanimation',
 'adultasachild',
 'adultchildfriendship',
 'adulter',
 'adulteri',
 'adulterousaffair',
 'adulterouswife',
 'adultery',
 'adultfilmmaking',
 'adulthood',
 'adulthumor',
 'adults',
 'advanc',
 'advancement',
 'advantag',
 'advantage',
 'advent',
 'adventur',
 'adventure',
 'adventurer',
 'adventures',
 'adventurous',
 'advers',
 'adversari',
 'adversaries',
 'adversary',
 'advertis',
 'advertising',
 'advertisingagency',
 'advertisingexecutive',
 'advertisingexpert',
 'advic',
 'advice',
 'advicecolumnist',
 'advis',
 'advisor',
 'advoc',
 'aegi',
 'aerial',
 'aerialcombat',
 'aeronautics',
 'aeroplan',
 'afar',
 'afdelingq',
 'affabl',
 'affair',
 'affairs',
 'affect',
 'affection',
 'affections',
 'afflict',
 'affluent',
 'afford',
 'afghan',
 'afghanistan',
 'afghanistanwar',
 'afk',
 'afoul',
 'afraid',
 'africa',
 'african',
 'africanamerican',
 'africanamericanchild',
 'africanamericandrama',
 'africanamericanhistory',
 'africanamericanhistorydrama',
 'africanhistory',
 'afro',
 'aft',
 'aftercreditsstinger',
 'aftercreditsstingeraction',
 'aftercreditsstingeradventure',
 'aftercreditsstingeranimation',
 'aftercreditsstingercomedi',
 'aftercreditsstingercomedy',
 'aftercreditsstingercrime',
 'aftercreditsstingerfamily',
 'aftercreditsstingerhorror',
 'aftercreditsstingerthriller',
 'afterlif',
 'afterlife',
 'aftermath',
 'afternoon',
 'ag',
 'againsttheodds',
 'agamemnon',
 'agatha',
 'age',
 'aged',
 'agedifference',
 'ageless',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agentadventure',
 'agents',
 'aggie',
 'aggress',
 'aggression',
 'aggressive',
 'aggressors',
 'agil',
 'aging',
 'agingactor',
 'agingsuperhero',
 'agn',
 'agnè',
 'ago',
 'agoraphobia',
 'agre',
 'agreement',
 'agrees',
 'agricultur',
 'agriculture',
 'agu',
 'ah',
 'ahab',
 'ahead',
 'ahmad',
 'ahsoka',
 'ai',
 'aid',
 'aida',
 'aidan',
 'aide',
 'aids',
 'ail',
 'aim',
 'aime',
 'aimless',
 'ain',
 'air',
 'airborn',
 'aircontroller',
 'aircraft',
 'aircraftcarrier',
 'aires',
 'airforce',
 'airforcebase',
 'airforceone',
 'airlin',
 'airline',
 'airpirate',
 'airplan',
 'airplane',
 'airplaneaccident',
 'airplanecrash',
 'airplanehijacking',
 'airplanepilot',
 'airplanewreck',
 'airport',
 'airportlounge',
 'airportsecurity',
 'airraid',
 'airship',
 'airtrafficcontrol',
 'aisl',
 'aisle',
 'aka',
 'akeelah',
 'akelarre',
 'aki',
 'akira',
 'al',
 'alabama',
 'aladdin',
 'alain',
 'alamo',
 'alan',
 'alarm',
 'alarmclock',
 'alaska',
 'alaskan',
 'alba',
 'albanian',
 'albeit',
 'albert',
 'alberteinstein',
 'alberto',
 'albino',
 'album',
 'albums',
 'alcatraz',
 'alcatrazprison',
 'alchemist',
 'alchemy',
 'alchemyfantasy',
 'alcohol',
 'alcoholabuse',
 'alcoholic',
 'alcoholicfather',
 'alcoholism',
 'aldo',
 'aldou',
 'alec',
 'alejandro',
 'alert',
 'alessandro',
 'alex',
 'alexa',
 'alexand',
 'alexander',
 'alexanderthegreat',
 'alexandr',
 'alexi',
 'alexia',
 'alexis',
 'alfi',
 'alfr',
 'algeria',
 'algerian',
 'algerianwar',
 'algorithm',
 'algren',
 'ali',
 'alias',
 'alibi',
 'alic',
 'alice',
 'alicia',
 'alien',
 'alienabduction',
 'alienation',
 'alienattack',
 'aliencontact',
 'aliencreature',
 'aliencreaturecomedy',
 'aliendnasciencefiction',
 'alienencounter',
 'alienfriendship',
 'alieninfection',
 'alieninvasion',
 'alieninvasionsciencefiction',
 'alienlanguage',
 'alienlife',
 'alienmonster',
 'alienparasites',
 'alienplanet',
 'alienplant',
 'alienpossession',
 'alienrace',
 'aliens',
 'alienspacecraft',
 'alienspaceship',
 'alientechnology',
 'align',
 'alik',
 'alike',
 'alin',
 'alisdair',
 'aliv',
 'alive',
 'allan',
 'alleg',
 'allegations',
 'allegedli',
 'allegi',
 'allegory',
 'allegra',
 'allen',
 'allerg',
 'allergy',
 'alley',
 'allgirlband',
 'alli',
 'allianc',
 'alliance',
 'allies',
 'allig',
 'alligator',
 'allison',
 'allow',
 'allowed',
 'allur',
 'ally',
 'alma',
 'almightyfantasy',
 'almási',
 'alon',
 'alongsid',
 'aloof',
 'alp',
 'alpha',
 'alphons',
 'alps',
 'alpsdrama',
 'alpsmountains',
 'alqaeda',
 'alreadi',
 'alt',
 'altar',
 'alter',
 'alterego',
 'altern',
 'alternatedimension',
 'alternatehistory',
 'alternatereality',
 'alternatetimeline',
 'alternateuniverseaction',
 'alternative',
 'alternativerealitycomedy',
 'alternativeuniverse',
 'alternativeworld',
 'altman',
 'alva',
 'alvin',
 'alway',
 'alyosha',
 'alyssa',
 'alzheimer',
 'amadeo',
 'amaia',
 'amali',
 'aman',
 'amanda',
 'amantido',
 'amass',
 'amateur',
 'amateurdetective',
 'amateurfootball',
 'amaz',
 'amazing',
 'amazon',
 'amazonian',
 'amazonrainforest',
 'amazonriver',
 'amazontribe',
 'ambassador',
 'amber',
 'ambigu',
 'ambiguity',
 'ambiguoushorror',
 'ambit',
 'ambiti',
 'ambition',
 'ambitions',
 'ambival',
 'ambivalent',
 'ambivalentcomedi',
 'ambul',
 'ambulance',
 'ambush',
 'amelia',
 'amend',
 'america',
 'american',
 'americana',
 'americanabroad',
 'americanbusinessman',
 'americancivilwar',
 'americancountrysidehorror',
 'americandream',
 'americanfootball',
 'americanfootballcoach',
 'americangiallocrime',
 'americangiallothriller',
 'americanhistorydrama',
 'americanmafia',
 'americanmidwest',
 'americans',
 'americanspycomedy',
 'americanwayoflife',
 'americanwest',
 'americanwilderness',
 'ami',
 'amiabl',
 'amid',
 'amidst',
 'amigos',
 'amin',
 'amish',
 'amiss',
 'amiti',
 'amityvil',
 'ammy',
 'amnesia',
 'amnesiac',
 'amok',
 'amor',
 'amoral',
 'amour',
 'amp',
 'ampezzo',
 'amphetamine',
 'ampl',
 'amplifi',
 'amputation',
 'amsterdam',
 'amulet',
 'amus',
 'amused',
 'amusedaction',
 'amusedcomedy',
 'amusementpark',
 'amy',
 'ana',
 'anachronism',
 'anachronistic',
 'anaconda',
 'anakin',
 'analog',
 'analogu',
 'analsex',
 'analysi',
 'analyst',
 'analyz',
 'anarchi',
 'anarchiccomedy',
 'anarchiccomedycomedi',
 'anarchiccomedycomedy',
 'anarchiccomedydrama',
 'anarchist',
 'anarchy',
 'anastasia',
 'anatolia',
 'ancestor',
 'ancestr',
 'ancestry',
 'anchor',
 'anchorman',
 'ancient',
 'ancientcivilization',
 'ancientcurse',
 'ancientegypt',
 'ancientevil',
 'ancientgreece',
 'ancientrome',
 'ancientwarfare',
 'ancientworld',
 'andalucia',
 'ander',
 'anderson',
 'anderton',
 'andesmountains',
 'andi',
 'andre',
 'andrea',
 'andrei',
 'andrew',
 ...]

In [19]:
from sklearn.metrics.pairwise import cosine_similarity

In [20]:
sim = cosine_similarity(vector)

In [21]:
sim

array([[1.        , 0.04299878, 0.00315675, ..., 0.01257477, 0.03498683,
        0.01824851],
       [0.04299878, 1.        , 0.        , ..., 0.00967069, 0.        ,
        0.02626284],
       [0.00315675, 0.        , 1.        , ..., 0.01469682, 0.00203751,
        0.        ],
       ...,
       [0.01257477, 0.00967069, 0.01469682, ..., 1.        , 0.01253565,
        0.03885282],
       [0.03498683, 0.        , 0.00203751, ..., 0.01253565, 1.        ,
        0.03427144],
       [0.01824851, 0.02626284, 0.        , ..., 0.03885282, 0.03427144,
        1.        ]], shape=(10000, 10000))

In [22]:
simdf = pd.DataFrame(sim,index=df['title'],columns=df['title'])

In [23]:
simdf

title,Inception,Interstellar,The Dark Knight,Avatar,The Avengers,Deadpool,Avengers: Infinity War,Fight Club,Guardians of the Galaxy,Pulp Fiction,...,A Dirty Shame,Buffet Froid,Poveri ma ricchissimi,Ewoks: The Battle for Endor,Precious Cargo,Final Set,Son in Law,My Dog Skip,Il vegetale,Boys Cry
title,,,,,,,,,,,,,,,,,,,,,
Inception,1.000000,0.042999,0.003157,0.012429,0.021769,0.013286,0.006790,0.000000,0.069776,0.033763,...,0.000000,0.029464,0.000000,0.015751,0.043911,0.014950,0.003519,0.012575,0.034987,0.018249
Interstellar,0.042999,1.000000,0.000000,0.070792,0.008759,0.000000,0.038749,0.016996,0.078511,0.014334,...,0.000000,0.012447,0.008630,0.000000,0.000000,0.002849,0.002168,0.009671,0.000000,0.026263
The Dark Knight,0.003157,0.000000,1.000000,0.000000,0.042162,0.043790,0.037455,0.000000,0.020397,0.024535,...,0.004862,0.014867,0.000000,0.001146,0.025157,0.006102,0.000000,0.014697,0.002038,0.000000
Avatar,0.012429,0.070792,0.000000,1.000000,0.000000,0.007990,0.034855,0.000000,0.022243,0.000000,...,0.000000,0.032948,0.000000,0.000000,0.010240,0.000000,0.000000,0.006722,0.000000,0.000000
The Avengers,0.021769,0.008759,0.042162,0.000000,1.000000,0.045429,0.118446,0.000000,0.168619,0.009735,...,0.004984,0.000000,0.000000,0.008563,0.017581,0.000000,0.000000,0.016007,0.021835,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Final Set,0.014950,0.002849,0.006102,0.000000,0.000000,0.015866,0.013126,0.016051,0.000000,0.007292,...,0.006676,0.029927,0.011919,0.011616,0.008333,1.000000,0.002387,0.018277,0.009650,0.003784
Son in Law,0.003519,0.002168,0.000000,0.000000,0.000000,0.003735,0.009157,0.000000,0.000000,0.000000,...,0.006358,0.020980,0.000000,0.000000,0.007549,0.002387,1.000000,0.015942,0.000000,0.006982
My Dog Skip,0.012575,0.009671,0.014697,0.006722,0.016007,0.013345,0.006820,0.000000,0.000000,0.003789,...,0.000000,0.018147,0.007660,0.002821,0.000000,0.018277,0.015942,1.000000,0.012536,0.038853
Il vegetale,0.034987,0.000000,0.002038,0.000000,0.021835,0.005298,0.004383,0.000000,0.000000,0.002435,...,0.000000,0.004817,0.009845,0.001813,0.013396,0.009650,0.000000,0.012536,1.000000,0.034271
Boys Cry,0.018249,0.026263,0.000000,0.000000,0.000000,0.013788,0.000000,0.000000,0.000000,0.023987,...,0.037787,0.021917,0.017770,0.030949,0.012099,0.003784,0.006982,0.038853,0.034271,1.000000

In [24]:
simdf['Inception'].sort_values(ascending=False)[1:6]

title
Inception: The Cobol Job    0.132968
House                       0.123113
The Matrix                  0.104004
Upgrade                     0.101389
The Matrix Revolutions      0.099702
Name: Inception, dtype: float64

In [25]:
import numpy as np

In [26]:
def recommend(movie):
    idx = df[df['title']==movie].index[0]
    movie_list = np.argsort(simdf.iloc[idx])[::-1][1:6]
    return df.iloc[movie_list].title.tolist()

In [27]:
recommend('Avatar')

['Skylines', 'Aliens', 'Predators', 'Apollo 18', 'Battle: Los Angeles']

In [28]:
df['poster_path']

0       /oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg
1       /gEU2QniE6E77NI6lCU6MxlNBvIx.jpg
2       /qJ2tW6WMUDux911r6m7haRef0WH.jpg
3       /kyeqWdyUXW608qlYkRqosgbbJyK.jpg
4        /RYMX2wcKCBAr24UyPD7xwmjaTn.jpg
                      ...
9995    /lNst0oa7VD0aJRR3if6ZjsQ3iwr.jpg
9996    /mCCa5AV51JHtCYWTB62Un8HM7Aw.jpg
9997    /A3TafOveMdmc1mzjCrmMBNa3oQ2.jpg
9998    /mI383Fhgvko8WzgjSDlplDHmro8.jpg
9999    /rZpkx4mEqglDaOEQvJMJ6hBKIUF.jpg
Name: poster_path, Length: 10000, dtype: object

In [29]:
print('https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg')

https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg

In [30]:
base_url = "https://image.tmdb.org/t/p/w500/"
print(base_url+"/brrgSFtcymZWaXl5a23GJRWdOSY.jpg")

https://image.tmdb.org/t/p/w500//brrgSFtcymZWaXl5a23GJRWdOSY.jpg

In [31]:
import pickle
with open(r'D:\netflix\similarity.pkl','wb') as f:
    pickle.dump(sim,f)